puppetlabs/pdksync

- README.md
Adding in a section on how to migrate a module from modulesync to pdksync.
> (maint) - Migrate from modulesync to pdksync README.

- lib/pdksync.rb
‘validate_autofix’ no longer called by sync method.
'pdk_convert' method separated out and created, currently uncalled.
> (maint) 'rubocop_autofix' renamed to 'validate_autofix'.

- .travis.yml
- lib/pdksync.rb
The ssh clone was failing due to the repo now being made public, updated to run with http to get tests running again.
Also updated the .travis file to conform to norms.
> Update travis and change ssh to https for git clone

- managed_modules.yml
This PR includes the following changes for `mananged_modules.yml`: 
- Removal of `## pdk update does not run well` section
- Slotted `## pdk update does not run well` modules into place (alphabetically)
> (maint) - Update list of managed modules

- README.md
- Rakefile
- lib/pdksync/constants.rb
This change allows a user to define their own configuration file that lives outside of the repo, instead of having to manually change hardcoded values in constants.rb
> (MODULES-7233) - Add configurable file option

- lib/pdksync.rb
- spec/lib/pdksync_spec.rb
Incorrect formatting of managed_modules can return the following error: 
```NoMethodError: undefined method `each' for "-pu":String```
This change implements a more verbose error stating the root issue.
> (MODULES-7192) - Improved error message for incorrect formatting

- README.md
- Rakefile
- lib/pdksync.rb
- lib/pdksync/constants.rb
- lib/pdksync/githubclient.rb
- lib/pdksync/gitlabclient.rb
- lib/pdksync/gitplatformclient.rb
- lib/pdksync/pullrequest.rb
- pdksync.gemspec
* Create a GitPlatformClient wrapper class with the methods required by
pdksync main
* Keep the interface unchanged, meaning pdksync main uses the same
methods as before, but now they are no longer Octokit-specific
* Create wrapper classes for Github and Gitlab API access, using
octokit/octokit.rb for Github and NARKOZ/gitlab for Gitlab
* Create a wrapper class for pull request objects abstracting the
differences between Github and Gitlab
* Keep Github and the Github API as defaults as before
* Extend configuration and constants for Git platform-specific settings
* Allow the user to configure which Git hosting platform to use
* Allow the user to configure the Git base URI under which to access
Git repositories
* Set default Git base URI according to configured Git platform
* Add sanity …
> (MODULES-8419) Refactor to add support for GitLab

- Rakefile
Includes:
* An update to the output message of show config
* An update to clean up the namespaces
After this PR the rake task output is like so:
`➜ pdksync git:(smallcleanups) ✗ bundle exec rake -T
rake changelog
rake git:clean_branches[branch_name]
rake git:clone_managed_modules
rake git:create_commit[branch_name,commit_message]
rake git:push_and_create_pr[pr_title,label]
rake pdksync[additional_title]
rake pdksync:pdk_convert
rake pdksync:pdk_validate
rake pdksync:run_a_command[command] '
rake pdksync:show_config `
> Includes two small cleanup items around messaging

- lib/pdksync.rb
This change will display a warning to the user if they are found to be using an older version of pdk than the current release.
> (MODULES-8730) Display warning on outdated pdk version

- lib/pdksync.rb
By moving the check for module repositories to the `clone` step, we save
22s startup time for all other pdksync commands. Once the repository is
cloned, we do not need additional reassurance that it exists on github.
```
david@davids:~/git/pdksync$ time bundle exec rake 'pdksync:run_a_command[pwd]' > /dev/null
real	0m22.996s
user	0m1.540s
sys	0m0.202s
david@davids:~/git/pdksync$ time bundle exec rake 'pdksync:run_a_command[pwd]' > /dev/null
real	0m0.825s
user	0m0.702s
sys	0m0.133s
david@davids:~/git/pdksync$
```
This change also makes the initialisation of the client optional, so it
does not allocate memory unless it is needed.
> (maint) 27x performance improvement

- Gemfile
- Rakefile
- pdksync.gemspec
- spec/utils_spec.rb
This is just a bit of cleanup but the big thing here is moving the pdk requirement to 1.10.0 or later. Without this pdksync users who have a very old version of pdk installed will run into issues.
> (maint) Add bundler tasks and pdk requirement

- README.md
The `:` at the end of the `git_base_uri` attribute is not required. Adding it to the `pdksync.yml` results in a remote clone of `git@github.com::$NAMESPACE/$REPO` which fails due to the double `::`
> (maint) Fix typo in README.md

- spec/spec_helper.rb
When a GITHUB_TOKEN was set in the environment, tests would fail with
```
1) PdkSync::Utils #self.setup_client
Failure/Error: PdkSync::GitPlatformClient.new(configuration.git_platform, configuration.git_platform_access_settings)
#<PdkSync::GitPlatformClient (class)> received :new with unexpected arguments
expected: (:github, {:access_token=>"github-token", :api_endpoint=>nil, :gitlab_api_endpoint=>"https://gitlab.com/api/v4"})
got: (:github, {:access_token=>"[secure]", :api_endpoint=>nil, :gitlab_api_endpoint=>"https://gitlab.com/api/v4"})
Diff:
@@ -1,5 +1,5 @@
[:github,
- {:access_token=>"github-token",
+ {:access_token=>"[secure]",
:api_endpoint=>nil,
:gitlab_api_endpoint=>"https://gitlab.com/api/v4"}]
```
> Improve spec_helper to avoid test failures

- lib/pdksync.rb
This check is both wrong (the variable is `gemfury_token`, not `@gemfury_token`) and useless, as `valid_access_token_gem_fury?` will throw an exception if there is no GEMFURY_TOKEN.
> fix gemfury testing upload

- managed_modules.yml
`bootstrap` is no longer supported by the modules team
> (maint) - Remove bootstrap from managed_modules

- README.md
- lib/pdksync.rb
- lib/pdksync/conf/puppet_abs_supported_platforms.yaml
- lib/pdksync/rake_tasks.rb
- lib/pdksync/utils.rb
The `pdksync:add_provision_list[:key, :provisioner, :images]` task
will add an entry to the `provision.yaml` with the params given.
The `generate_vmpooler_release_checks[:puppet_version]` task will
create an entry in the `provision.yaml` that will generate a
release checks configuration (using the ABS provisioner) that
satisfies both of these requirements:
- The supported platforms of the given Puppet version
- The supported platforms of the module
This ensures that there is the maximum coverage for each Puppet
version on each module, without any unecessary platforms being
tested.
The Puppet version's test platforms are defined in the config file
`lib/pdksync/conf/puppet_abs_support_platforms.yaml`.
> Add tasks to add / update entries in module's provision.yaml

- managed_modules.yml
This module has been deprecated.
> (maint) Removing Azure from managed modules list

- managed_modules.yml
Team no longer maintains this module: https://puppetlabs.github.io/iac/modules/
> (maint) Removing resource

- lib/pdksync/utils.rb
Reverts puppetlabs/pdksync#166
> Revert "(GH-cat-8) Move CentOS 8 support to CentOS Stream 8"

- managed_modules.yml
See additional blog post for more information on the removal of support:
https://puppetlabs.github.io/content-and-tooling-team/blog/posts/2022-06-30-changes-to-supported-modules/
> (maint) - Removal of modules no longer supported

- lib/pdksync/logger.rb
- lib/pdksync/utils.rb
For some reason, there was a `self.crit` method in `logger.rb` (calling `logger.error`), but no `self.error`.
There was only one instance of `Logger.crit` in the code, but three instances of `Logger.error` that would all explode with
```
NoMethodError: undefined method `error' for PdkSync::Logger:Class
```
Fixes #172
> Fix `Logger.error`

- managed_modules.yml
Prior to this commit the managed_modules list was not inline with the modules the team support.
This commit removes modules and adds mount_iso.
> (MAINT) Update list of supported modules

- spec/utils_spec.rb
Prior to this commit the unit test was failing as the reference on the template has changed. 
Updating the test to be inline with the current test data.
PDKSync is cloning puppetlabs-motd and checking its currently metadata.json file which now looks different from when the initial pdksync tests were written: https://github.com/puppetlabs/puppetlabs-motd/blob/93f8597c24a86df550e8406b62c629d8f215d5bb/metadata.json#L100
> (maint) Update unit test expectation

- Gemfile
- Rakefile
Prior to this commit we were using old gems that are no longer used. We don't use Travis anymore and also the changelog generator. As they are old dependencies they are brining in a version of activesupport that has a CVE.
Removing the gems will stop us bringing in old dependencies we no longer need.
N/A
> (maint) Removal of old obsolete gems

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .rubocop.yml
- Gemfile
- spec/pdksync_spec.rb
- spec/utils_spec.rb
Adds Ruby 3.x support to pdksync.
> (CONT-1138) - Add ruby 3.x compatibility

- lib/pdksync.rb
Validate that each module exists only once, as that module is being processed.
During module cloning, the module validation function is called for all modules on each iteration
through the module list, resulting in the cloning taking much longer than it needs to.
This change adjusts the code to validate one module at a time as that module is being
processed.
> Improve module validation performance

- README.md
Prior to this commit there is an additional square bracket that is not required:
> (maint) Remove unnecessary square bracket

- Gemfile
Following a recent team decision, we are implementing a Rubocop Upgrade, moving the version from 1.48.1 to 1.50.0. This should be the final version until Puppet 7 is unsupported.
> (CAT-1688) - Pin rubocop to `~> 1.50.0`

- pdksync.gemspec
- spec/spec_helper.rb
(CAT-1618) - Remove deprecated/obsolete codecov gem
pdk version: `3.0.0`
> pdksync - (CAT-1618) - Remove deprecated/obsolete codecov gem

- lib/pdksync/utils.rb
When running the run_tests_locally rake tasks I noticed unnecessary whitespace when stdout has nothing to log.
I have updated run_command in utils so that stdout will not log when there is nothing to log 
Before
```
INFO - PdkSync: puppetlabs-chocolatey, 
INFO - PdkSync: Run tests 
INFO - PdkSync: 
INFO - PdkSync: 
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /Users/alex.patterson/Library/CloudStorage/OneDrive-PERFORCESOFTWARE,INC/Desktop/pdksync/lib/pdksync/utils.rb:256)
INFO - PdkSync: SUCCESS:Kicking of module Acceptance tests to run for the module puppetlabs-chocolatey - SUCCEED.Results will be available in the …
```
> Updated run_command to not log when there is nothing to log

- lib/pdksync/utils.rb
- spec/pdksync_spec.rb
When fetching tests locally I have added an error warning to make it more obvious when litmusacceptance.out doesn't exist, and cleaned up the error output
Before
```
INFO - PdkSync: puppetlabs-lvm, 
INFO - PdkSync: Fetch test results for local run 
WARN - PdkSync: (WARNING) Fetching test results locally supports only for litmus'
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - modules_pdksync/puppetlabs-lvm/litmusacceptance.out (Errno::ENOENT)
/Users/alex.patterson/Library/CloudStorage/OneDrive-PERFORCESOFTWARE,INC/Desktop/pdksync/lib/pdksync/utils.rb:626:in `readlines'
/Users/alex.patterson/Library/CloudStorage/OneDrive-PERFORCESOFTWARE,INC/Desktop/pdksync/lib/pdksync/utils.rb:626:in `fetch_test_results_locally' …
```
> Throw an error if litmusacceptance.out doesn't exist

- lib/pdksync/utils.rb
- spec/pdksync_spec.rb
When running e.g. ```bundle exec rake 'pdksync:remove_platform_from_metadata[ubuntu, 18.04]'```
the os will not be removed from the metadata.json of a module due to the character casing not matching "Ubuntu"
To resolve this I have updated remove_platform_from_metadata so that when removing a platform the os character case is ignored
> Ignore case when removing operating systems

- lib/pdksync.rb
When running the pdksync:test_results_jenkins task I have added a error log to make it more obvious that the results_puppetlabs-lvm.out does not exist
> Throw error if jenkins test results do not exist

- README.md
This PR adds setup instruction that will work for modules or gems that require puppetcore (puppet or facter).  These instructions are backward compatible.  Since most repositories/modules are not yet puppetcore enabled, the `pdksync` should work as before; however, as more and more become linked to puppetcore then these instructions will enable the seamless operation.
Since puppet and facter are not included in either the gemspec or Gemfile, then only a doc change here is required.
> Add puppetcore enablement instruction

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .rubocop.yml
- README.md
- pdksync.gemspec
Puppet 7 is EOL. Therefore, we can remove the test infrastructure for it. This commit aims to clear up any testing/config infrastructure related to Puppet 7 and, by extension, Ruby 2.7.
> (CAT-2281) Remove puppet 7 infrastructure
