- README.md
> (MODULES-7194) README edits

- README.md
Updating as I put in the incorrect URL.
> (maint) - Update blog post url

- managed_modules.yml
Request to review the small changes
> (CLOUD-2094) adding container modules to the list

- lib/pdksync.rb
Currently all changes are added/staged even if there are no code changes. This change will only add files if there are changes that have been made.
> (maint) - Don't add files to staged if there are no changes

- managed_modules.yml
> (Adding cloud module helm)

- CHANGELOG.md
- Rakefile
- pdksync.gemspec
> MODULES-9693 Release Prep 0.5.0

- CODEOWNERS
Adding a default CODEOWNERS file. Please update if @puppetlabs/pdk needs to be added as well.
> (maint) Add initial CODEOWNERS file.

- .rubocop.yml
- lib/pdksync.rb
- lib/pdksync/utils.rb
- spec/fixtures/fake_managed_modules.yaml
- spec/pdksync_spec.rb
- spec/spec_helper.rb
- spec/utils_spec.rb
* Refactors the existing code to use the util module
which gives a much cleaner look for development.
* Add a utility module
This will be required in order to complete #107 and #108 
Since there is no tests for testing the individual rake tasks I am not 100% that those rake tasks will run cleanly. The rake tests should be manually tested as a result before merging this. 
This will also likely cause other PRs to update their code as any new methods would be added to the utils module.
> (maint) Updates pdksync to use new util module

- README.md
- lib/pdksync.rb
- lib/pdksync/configuration.rb
- lib/pdksync/rake_tasks.rb
- lib/pdksync/utils.rb
- spec/pdksync_spec.rb
- spec/utils_spec.rb
Request for a review.
This PR provides feature to perform the testing of multi-gem (puppet-module-gem)
1.Cloning the gem
2.Building and pushing changes to gemfury account for testing
3. Update Gemfile with the new gem built.
Testcases are added to pdksync_spec & util_spec files.
Updated the readme with instructions on the new rake task.
> (MODULES-10379) Multi Gem testing

- README.md
- spec/pdksync_spec.rb
Request for a review
Updated readme for multi gem testing
Fix pdksync unit testcases for failures around GIT_PATH with latest git released
> (FM-8875) Update the readme for multigem and fix unit testcase error

- README.md
- lib/pdksync.rb
- lib/pdksync/rake_tasks.rb
Fixed the rake parameter
Fixed the version
Fixed the readme
> (maint) fix gemfury upload

- lib/pdksync/utils.rb
> (MODULES-8440) Ensure pdksync works on windows

- .gitignore
- README.md
Update the `README` for the following new Rake tasks:
- add_platform_to_metadata
- remove_platform_from_metadata
- update_requirements
- normalize_metadata_supported_platforms
> (MAINT) Update README.md; Add '.idea' to .gitignore

- README.md
- lib/pdksync/utils.rb
- spec/utils_spec.rb
Removal of any offensive or inappropriate terminology from the code base.
> (IAC-1447) - Removal of Inappropriate Terminology

- managed_modules.yml
These modules are deprecated and no longer need maintained.
> (maint) Removing deprecated modules

- lib/pdksync.rb
- lib/pdksync/utils.rb
- spec/pdksync_spec.rb
- spec/utils_spec.rb
> (GH-148) Fix logging for pdksync:pdk_validate task

- README.md
> (GH-155) Add guide to README for Github token reqs

- README.md
Closes https://github.com/puppetlabs/pdksync/issues/160
> (CONT-1217) - README Update for rake -D

- README.md
Provide a detailed description of all the changes present in this pull request.
> (CONT-1216) - Update README

- .github/workflows/mend.yml
Provide a detailed description of all the changes present in this pull request.
> (CAT-1311) Update mend.yml to consume tooling report config

- managed_modules.yml
> Adding 3 new modules

- managed_modules.yml
removing device-manager as it is depreciated 
> removing device-manager as it is depreciated 

- Gemfile
Reverts puppetlabs/pdksync#214
> Revert "(maint) Exclude breaking rubocop versions"
